package EasyAlgorithm.type;

public enum EasyAlgorithmType {
    TWO_SUM,
    SUM_OF_DIGITS_OF_STRING_AFTER_CONVERT,
    PALINDROME_NUMBER,
    ROMAN_TO_INT,
    LONGEST_COMMON_PREFIX,
    MERGE_TWO_SORTED_LISTS,
    SCORE_OF_A_STRING,
    VALID_PARENTHESES,
    LENGTH_OF_LAST_WORLD
}
